//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill : EntityValidator
    {
        public string ID { get; set; }
        public string DeliveryID { get; set; }
        public string EmployeeID { get; set; }
        public string AgencyID { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
