using DevExpress.DashboardCommon;
using DevExpress.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data.Entity;

namespace FinalProject
{
    public partial class Dashboard2 : DevExpress.DashboardCommon.Dashboard
    {
        public Dashboard2()
        {
            InitializeComponent();
            
            FinalProject.dotNET_FinalProjectEntities dbContext = new FinalProject.dotNET_FinalProjectEntities();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.DeliveryDetails.Load();
            // This line of code is generated by Data Source Configuration Wizard
            dashboardObjectDataSource2.DataSource = dbContext.DeliveryDetails.Where(x => x.Delivery.EmployeeID == Program.userID).ToList();
        }
    }
}
