//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Received : EntityValidator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Received()
        {
            this.ReceivedDetails = new HashSet<ReceivedDetail>();
        }
        [Required, StringLength(10, ErrorMessage = "Please enter valid ID")]
        public string ID { get; set; }
        public string EmployeeID { get; set; }
        [Required(ErrorMessage = "Please choose Supplier")]
        public string SupplierID { get; set; }
        [Required(ErrorMessage = "Please choose Date")]
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivedDetail> ReceivedDetails { get; set; }
    }
}
